### ISSUE TITLE
Get the "visible" content from the session

### ISSUE THREAD

**Issue by IonicaBizau** [chjj/pty.js#100]
Is it possible to get a string with the visible content in the bash session?

My scenario is:

 1. I create a pty.js instance when the first client comes.
 2. When new clients come, I use the already created instance of pty.js
 
How can I update the other clients sending the existing content from the first instance?

I tried to have an array `_data` where I push the chunks that come `on("data", ...)`. Then when new clients come I iterate the array and emit `socket.emit("data", _data[i])`.

This is not working after I open and close VIM (e.g.).

**Comment by chjj** [comment]
> Is it possible to get a string with the visible content in the bash session?

No. Not unless you're using something like https://github.com/chjj/term.js. You need a real terminal to tell what is visible and what isn't.

**Comment by IonicaBizau** [comment]
Ok, got it! Thanks for creating awesome tools: it's interesting seeing that `marked` is created by you. :smile:  I use it in a project, but I didn't notice that you are its creator. :+1:

Same thing with `blessed`. Oh, and you work at Go Daddy! :smiley: Keep up the good work!
