### ISSUE TITLE
Use net.Socket instead of tty.ReadStream for master side of pty.

### ISSUE THREAD

**Issue by socketpair** [chjj/pty.js#101]
``term.socket.setRawMode()`` will NOT work since kernel 3.19
See https://github.com/torvalds/linux/commit/6460fbbf476ad8d4f4196534c00019975b33e1db

And also, opened ``/dev/ptmx`` - SHOULD NOT be terminal really.  But today this is still terminal device. So, API valid for stdin/stdou/stderr in nodejs IS NOT suitable for ``/dev/ptmx``, since it IS NOT terminal.

So, as I think, some changes required. At least you should not use ``tty.ReadStream`` and use ``net.Socket`` instead. Also, you CAN change class without any API breaking.

**Comment by chjj** [comment]
Have you tested this? pty.js originally used net.Socket until node internals changed which would *not* allow tty fds to be passed into net.Socket. We had to switch to using tty.ReadStream, which accepts tty fds.

**Comment by socketpair** [comment]
In new kernel version, ``isatty(open(/dev/ptmx))`` will return 0, and net.Socket() will work as expected.

**Comment by socketpair** [comment]
my fail:

```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, char* argv[])
{
        int fd = open("/dev/ptmx", O_RDWR);
        printf("isatty returns %d\n", isatty(fd));
        close(fd);
        return 0;
}
```
prints ``1``. I will write to Peter Hurley <peter@hurleysoftware.com> that should be fixedin nex linux kernel. If not, /dev/ptmx become very-cutted TTY. No real ioctls works, but say that this is TTY. Also, /dev/ptmx cannot become session leader, proof:

```
$ uname -a
Linux mmwork 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ sudo setsid sh -c 'exec 3<>/dev/ttyS0; ps -opid,tty | fgrep $$; '
14000 ttyS0
$ sudo setsid sh -c 'exec 3<>/dev/ptmx; ps -opid,tty | fgrep $$; '
14004 ?
```

**Comment by socketpair** [comment]
Linux is shit :(. I have talk with Peter Hurley, and he describe me how this works. You don't need to change anything.
