### ISSUE TITLE
pty.js errors with recent build of nodejs?

### ISSUE THREAD

**Issue by psychemedia** [chjj/pty.js#109]
I've been running a legacy virtual machine for some time and rebuilt it today with presumably a new version of nodejs that is causing the following error when trying to run tty.js:

```
Error: Execution of '/usr/local/bin/npm install --global tty.js' returned 1: > pty.js@0.2.3 install /usr/local/lib/node_modules/tty.js/node_modules/pty.js
==> tm351lts: > node-gyp rebuild
==> tm351lts: 
==> tm351lts: gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/vagrant/.node-gyp/0.12.0"
==> tm351lts: gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tty.js/node_modules/pty.js/.node-gyp"
==> tm351lts: child_process: customFds option is deprecated, use stdio instead.
==> tm351lts: make: Entering directory `/usr/local/lib/node_modules/tty.js/node_modules/pty.js/build'
==> tm351lts:   CXX(target) Release/obj.target/pty/src/unix/pty.o
```

Any pointers for a workaround much appreciated.

**Comment by chjj** [comment]
That's an odd error message, but tty.js was using an old pty.js version. I quickly updated it just now. Try again.

**Comment by IonicaBizau** [comment]
This is most probably because you're trying to install a global package but you don't have write permissions. 

To solve it I recommend [configuring NPM *not* require `sudo`](https://github.com/IonicaBizau/dotfiles#npm-config). However, you can still do it with root access.

**Comment by chjj** [comment]
Thanks @IonicaBizau. Closing for now.
