### ISSUE TITLE
gyp: deps\winpty\winpty.gyp not found (cwd: C:\CI-Cor\gecko-shell\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by lygstate** [chjj/pty.js#113]
C:\CI-Cor\gecko-shell>npm install pty.js cls
|
> pty.js@0.2.6 install C:\CI-Cor\gecko-shell\node_modules\pty.js
> node-gyp rebuild

C:\CI-Cor\gecko-shell\node_modules\pty.js>node "C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp: deps\winpty\winpty.gyp not found (cwd: C:\CI-Cor\gecko-shell\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\CI-Cor\gecko-shell\node_modules\pty.js
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\\\node.exe" "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pty.js" "cls"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\CI-Cor\gecko-shell\npm-debug.log

C:\CI-Cor\gecko-shell>

**Comment by IonicaBizau** [comment]
Same error on Ubuntu 15.04, running node `v0.11.15`.

**Comment by mscdex** [comment]
+1 It looks like `deps/` is not included in the published tarballs. @chjj Any chance to fix this (possibly to do with `.gitignore`)?

**Comment by chjj** [comment]
Will double check. Strange I never ha any problems before.

**Comment by chjj** [comment]
Ah, I forgot to grab the winpty submodule when I recloned all my repos (new laptop). That's why it wasn't included. v0.2.7-1 should fix this.

**Comment by mscdex** [comment]
Thanks!

**Comment by SomeoneWeird** [comment]
It seems like this is an issue again.

**Comment by briangleeson** [comment]
Yep just ran into this issue myself

**Comment by CarbonChili** [comment]
Use node-pty instead. Where the program references pty.js as a require change this to node-pty instead.

var pty = require('pty.js');
to
var pty = require('node-pty');

As far as I can tell there seems to be an issue with compiling pty.js on windows.
