### ISSUE TITLE
resource leak when run in multple asynchronous processes

### ISSUE THREAD

**Issue by jfelten** [chjj/pty.js#123]
Testing with bash on CentOS 7 as well as OSX:

Spawning a pty.js object in multiple asynchronous method calls leaves hanging processes.  These processes will persist forever even after the main node.js process terminates on the server until a reboot or killed manually.  "term.destroy()" does not completely clean up when multiple pty.js objects are instantiated simultaneously.  This is not a problem when multiple pty.js objects run synchronously one at a time. 

My work around is to spawn the pty.js objects in separate processes, which eliminates this problem.

I thought I should at least make you all aware.  This seems to occur in both node.js v10.x and 12.x.  pty.js does not work for me on 11.x due to joyent#8468.  I am using pty.js version: 0.2.6.

**Comment by chjj** [comment]
This should be fixed now with v0.2.9. pty.js now reads the exit codes of the processes. There shouldn't be anymore zombies.
