### ISSUE TITLE
upon killing the process: FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope 

### ISSUE THREAD

**Issue by intval** [chjj/pty.js#126]
If the spawned process dies for any reason, node irrecoverably crashes with
```
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
```

# Script to reproduce:
```
var pty = require('pty.js');
var proc = pty.spawn('bash');
setTimeout(function(){proc.kill();}, 1000);
```

# Expected outcome:
- No crash
- Event raised on error / on exit

# Additional info
```
vagrant@precise64:/vagrant/replserver$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

iojs 2.5.0
```
$ node -e "console.log(process.versions)"
{ http_parser: '2.5.0',
  node: '2.5.0',
  v8: '4.2.77.21',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '44',
  openssl: '1.0.2d' }
```

**Comment by intval** [comment]
Or, perhaps, what would be the proper way to shutdown the forked process without causing troubles ?

**Comment by intval** [comment]
Actually this happens not only on process kill, but also on a valid exit, such as  
`proc.write("exit\r");` for bash, which supposedly terminates the process in a nice way

**Comment by chjj** [comment]
This looks like a difference in v8 API between io.js 2.5.0 and node.js 0.12.x.  io.js uses v8 4.2 node uses v8 3.28.

It looks like this has something to do with pty_after_waitpid not creating a NanScope() to execute the callback: https://github.com/chjj/pty.js/blob/master/src/unix/pty.cc#L449

I don't normally use io.js, but I just tested this change on 2.5.0 and it seems to fix it.

**Comment by intval** [comment]
Wow, you are awesome ;) Thanks for such a prompt reply and fix. It works indeed.
