### ISSUE TITLE
Fails to build: relocation error

### ISSUE THREAD

**Issue by JensenPaul** [chjj/pty.js#146]
A description of the issue is here:
http://stackoverflow.com/questions/28289610/how-do-you-link-external-shared-libraries-to-a-native-extension
which is copied from:
https://github.com/dart-lang/sdk/issues/22257#c4

I can build it myself with these commands:
$ make clean
$ make
$ g++ -fPIC -c src/unix/pty.cc -o build/Release/obj.target/pty/src/unix/pty.o -I node_modules/nan -I ~/.c9/node/include/node
$ make

Here's what normally happens:
$ ~/.c9/node/bin/node ~/.c9/node/bin/npm install .

> pty.js@0.3.0 install /tmp/pty.js
> node-gyp rebuild

make: Entering directory `/tmp/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
/usr/bin/ld: Release/obj.target/pty/src/unix/pty.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
Release/obj.target/pty/src/unix/pty.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/pty.node] Error 1
make: Leaving directory `/tmp/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (~/.c9/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "node" "~/.c9/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "~/.c9/node/bin/node" "~/.c9/node/bin/npm" "install" "."
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/pty.js/npm-debug.log

**Comment by jmls** [comment]
any news on this ? I think I've just hit it :(

**Comment by JensenPaul** [comment]
I just realized I had the GYP_DEFINES environment variable set to "OS=android".  Clearing this environment variable fixed the issue for me.
