### ISSUE TITLE
Any chance to make pty.js compatible with Node 0.11.x ?

### ISSUE THREAD

**Issue by Unitech** [chjj/pty.js#88]
I manage to modify and install pty.js but it doesn't work with Node.js 0.11.13.

Is there any plan or any patch that could make it work with newer node version ?

Thanks

**Comment by rektide** [comment]
Activity in that node ticket, asking if this is still a problem.

**Comment by jshkurti** [comment]
It has been fixed a while ago by @chjj I don't remember the exact commit.
I guess we can close this :)
