### ISSUE TITLE
Node Gyp Compile error on OS X

### ISSUE THREAD

**Issue by CharlotteGore** [chjj/pty.js#93]
Haven't been able to install pty.js since I upgraded Xcode on this system. 

~~~sh
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
~~~

This is what I'm getting when trying to install it:

~~~sh
$ npm install pty.js
\
> pty.js@0.2.4 install /Users/charlotte/Documents/Repos/CodeboxRepo/node_modules/pty.js
> node-gyp rebuild

gyp WARN EACCES user "[whatever]" does not have permission to access the dev dir "/Users/[whatever]/.node-gyp/0.10.32"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/3s/4v45nyg17_gdt_q2g603kfvr0000gn/T/.node-gyp"
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:487:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:533:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/charlotte/Documents/Repos/CodeboxRepo/node_modules/pty.js
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "pty.js"
npm ERR! cwd /Users/[whatever]/Documents/Repos/CodeboxRepo
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
~~~

**Comment by OKNoah** [comment]
@EloB 

I get an error doing that workaround too

    Users-Air:javascript_practice user$ npm install -g git+https://github.com/chjj/pty.js.git

    > pty.js@0.2.4 install /usr/local/lib/node_modules/pty.js
    > node-gyp rebuild

      CXX(target) Release/obj.target/pty/src/unix/pty.o
    ../src/unix/pty.cc:37:10: fatal error: '/usr/include/util.h' file not found
    #include </usr/include/util.h>
             ^
    1 error generated.
    make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Darwin 14.0.0
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/local/lib/node_modules/pty.js
    gyp ERR! node -v v0.10.34
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok

    npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the pty.js@0.2.4 install script.
    npm ERR! This is most likely a problem with the pty.js package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls pty.js
    npm ERR! There is likely additional logging output above.
    npm ERR! System Darwin 14.0.0
    npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "git+https://github.com/chjj/pty.js.git"
    npm ERR! cwd /Users/user/Documents/dev/javascript_practice
    npm ERR! node -v v0.10.34
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

**Comment by carlosbaraza** [comment]
Hi @chjj,

The last commit did not fix the issue, at least for me. A working version could be found in this pull request: https://github.com/chjj/pty.js/pull/106

Thank you.

**Comment by chjj** [comment]
See #104 and #106.
