### ISSUE TITLE
Add option for not overriding stderr of child process

### ISSUE THREAD

**Issue by socketpair** [chjj/pty.js#99]
I need to run pppd as child process. PPPD use stderr to write errors. If these errors gets intermixed with ppp stdout, I will receive trash (instead of ppp packets) from master socket. So, If stderr of child process will not be touched (inherited from parent) -- it will solve that weird problem.

**Comment by dannydulai** [comment]
the entire point of pty.js is to use a pty... why are you using pty.js instead of http://nodejs.org/api/process.html ?

**Comment by socketpair** [comment]
PPPd requires terminal on it's stdin/stdout. And not require that stderr also be terminal. AFAIK, process API in nodejs does not provide option to allocate terminal.

**Comment by chjj** [comment]
pty's have no stdout or stderr. They're just one bidirectional pipe fd. What you're asking is impossible. The pty fd doesn't point to a process. It points to a terminal containing a foreground process, so you lose the ability to have an stderr.

**Comment by socketpair** [comment]
No, you not understand right.

In current situation, when process is run, opened /dev/pts/xxxx id duplicated (dup2()) to stdin,stdou and stderr of child process. This is OK for running shell (like bash) and not OK for running pppd.

It will be nice if you can make an option to not overriding stderr of child process. In that case, stderr of child process should point to same file descriptor as in parent process.

Please reopen.
